name: SteamBot News

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  enviar-noticias:
    name: Enviar Notícias da Steam por E-mail
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Descriptografar secrets.json
        run: |
          echo "${{ secrets.SECRETS_KEY }}" > key.txt
          openssl aes-256-cbc -d -a -pbkdf2 -in utils/secrets.json.enc -out utils/secrets.json -pass file:./key.txt
          rm key.txt

      - name: Executar bot
        run: python SteamBot.py
        
      - name: Commit e push de index.html e banco.db
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add index.html
          git commit -m "Chore: atualiza index.html com as noticias do dia via GitHub Actions" || true

          git add dados.db
          git commit -m "Chore: atualiza banco de dados com as noticias do dia e removendo as excedentes via GitHub Actions" || true

          git diff --quiet HEAD || git push
