name: SteamBot News

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  enviar-noticias:
    name: Enviar Notícias da Steam por E-mail
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Descriptografar secrets.json
        run: |
          echo "${{ secrets.SECRETS_KEY }}" > key.txt
          openssl aes-256-cbc -d -a -pbkdf2 -in utils/secrets.json.enc -out utils/secrets.json -pass file:./key.txt
          rm key.txt

      - name: Executar bot
        run: python SteamBot.py
        
      - name: Commit e push de index.html e banco.db
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add index.html dados.db
          git commit -m "Update: atualiza index.html e banco de dados via GitHub Actions" || echo "Nenhuma notícia nova"
          git push